import test from 'node:test';
import assert from 'node:assert/strict';
import {parseCsv,csvRows,inferCsvLayout,validateRows,textRows,csvCell,resultsCsv,normalized,cosine,buildCentroids,classifyEmbedding,PROTOTYPES,PREFIX} from '../core.js';
test('text ignores blank rows',()=>assert.deepEqual(textRows(' a \n\nb\r\n'),['a','b']));
test('one-column csv with BOM and CRLF',()=>assert.deepEqual(parseCsv('\ufeffreview\r\n"a"\r\n"b"'),[['review'],['a'],['b']]));
test('quoted commas and escaped quotes',()=>assert.deepEqual(parseCsv('"a,b","say ""hi"""'),[['a,b','say "hi"']]));
test('multiline CSV stays one review',()=>assert.deepEqual(csvRows(parseCsv('review\n"line1\nline2"'),0,true),['line1\nline2']));
test('reject unclosed quote',()=>assert.throws(()=>parseCsv('"no')));
test('reject quote inside bare cell',()=>assert.throws(()=>parseCsv('a"b')));
test('reject junk after quote',()=>assert.throws(()=>parseCsv('"a"b')));
test('reject uneven CSV columns',()=>assert.throws(()=>parseCsv('a,b\na')));
test('reject empty CSV',()=>assert.throws(()=>parseCsv('  \n')));
test('header infer finds review column',()=>assert.deepEqual(inferCsvLayout([['id','review'],['1','x']]),{header:true,column:1}));
test('single column no false known header',()=>assert.deepEqual(inferCsvLayout([['useful']]),{header:false,column:0}));
test('headerless multi CSV can explicitly select',()=>assert.deepEqual(csvRows([['1','x'],['2','y']],1,false),['x','y']));
test('empty review rejected',()=>assert.throws(()=>validateRows([])));
test('100 rows accepted',()=>assert.equal(validateRows(Array(100).fill('ok')).length,100));
test('101 rows rejected, not truncated',()=>assert.throws(()=>validateRows(Array(101).fill('ok'))));
test('2001 chars rejected',()=>assert.throws(()=>validateRows(['x'.repeat(2001)])));
test('2000 chars accepted',()=>assert.equal(validateRows(['x'.repeat(2000)])[0].length,2000));
test('total character bound enforced',()=>assert.throws(()=>validateRows(Array(100).fill('x'.repeat(1001)))));
test('HTML remains inert text',()=>assert.deepEqual(parseCsv('<img src=x onerror=alert(1)>'),[['<img src=x onerror=alert(1)>']]));
test('formula CSV cell protected',()=>assert.equal(csvCell('=HYPERLINK("x")'),'"\'=HYPERLINK(""x"")"'));
test('leading whitespace formula protected',()=>assert.equal(csvCell('  +1'),'"\'  +1"'));
test('ordinary Japanese preserved',()=>assert.equal(csvCell('良い商品'),'"良い商品"'));
test('empty embeddings rejected',()=>assert.throws(()=>normalized([0,0])));
test('NaN embeddings rejected',()=>assert.throws(()=>normalized([NaN,1])));
test('unit normalized',()=>assert.deepEqual(normalized([3,4]),[.6,.8]));
test('cosine normal unit vectors',()=>assert.equal(cosine([1,0],[0,1]),0));
test('dimension mismatch rejected',()=>assert.throws(()=>cosine([1],[1,2])));
test('classification uses embedding centroids',()=>{const vectors=PROTOTYPES.map((_,i)=>[0,1,2,3].map(k=>Math.floor(i/4)===k?1:0)),cs=buildCentroids(vectors),r=classifyEmbedding([0,1,0,0],cs,vectors);assert.equal(r.category,'negative');assert.equal(r.score,1);});
test('tied scores are held',()=>{const vectors=PROTOTYPES.map((_,i)=>[0,1,2,3].map(k=>Math.floor(i/4)===k?1:0));const r=classifyEmbedding([1,1,0,0],buildCentroids(vectors),vectors);assert.equal(r.category,'hold');assert.equal(r.reason,'margin');});
test('classification task prefix exact',()=>assert.equal(PREFIX,'task: classification | query: '));
test('CSV export includes input and method without model branding',()=>{const x=resultsCsv([{id:1,text:'new text',category:'positive',candidate:'positive',score:.8,margin:.3,nearest:'example'}],'MODEL','REV');assert.ok(x.startsWith('\ufeff'));assert.ok(x.includes('new text'));assert.ok(!x.includes('MODEL'));assert.ok(!x.includes('model_revision'));assert.ok(!/gemma/i.test(x));assert.ok(x.includes('not probability'));});
